site_name: Khóa học python căn bản
site_url: https://fin68.vn/academy/python/basic

theme:
  name: material
  language: vi
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections      # nhóm mục trong sidebar trái
    - navigation.expand        # auto mở nhánh đang xem
    - navigation.tracking
    # - navigation.tabs        # tùy, nếu không muốn tabs thì bỏ
    - search.suggest
    - search.highlight
    - navigation.footer
    - header.autohide
    - content.code.copy
    - content.code.annotate    # hiển thị chú thích code dạng callouts
  palette:
    - scheme: slate            # mặc định dark giống ảnh
      toggle:
        icon: material/weather-sunny
        name: Giao diện sáng
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Giao diện tối
  logo: assets/logo.png
  favicon: assets/favicon.webp

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]
          options:
            docstring_style: numpy
            separate_signature: true
            merge_init_into_class: true
            members_order: source
            show_source: false
            show_if_no_docstring: false
            show_symbol_type_toc: true
            show_root_heading: false
            heading_level: 2
            signature_crossrefs: true
            extra:
              prefer_stubdocstring: true
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
      title: On this page        # nhãn giống ảnh
    # LƯU Ý: KHÔNG dùng toc.integrate để giữ TOC ở sidebar phải
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.inlinehilite

extra:
  # Bỏ repo_url/edit_uri nếu chưa có repo để tránh hiện nút Edit/View
  generator: false

extra_css:
  - assets/theme.css           # map màu theo Tailwind DS (tuỳ chọn)
extra_javascript:
  - assets/fin68-ui.js
nav:
  - Giới thiệu: index.md
  - Syllabus: syllabus/index.md
  - Câu hỏi thường gặp (FAQ): faq.md



